### this is workflow.yaml
### /home/irina/SegLine/src/config/paths.yaml

params:
  splitting_method: "length"  # choose to split plots/subplots by fixed "length" or fixed "area"

dataset:
  ground_footprint: "C:/Users/nicolebyford/Documents/Bohn_2025/Footprint/0_BTools/v2/2_final_footprint/Bohn_FLM_2fixedwidth_v2_QC.shp"
  ground_footprint_layer: null      # null if NO layer
  centerline: "C:/Users/nicolebyford/Documents/Bohn_2025/Footprint/0_BTools/v2/2_final_footprint/Bohn_FLM_1centerlines_dissolved_v2_QC.shp"
  centerline_layer: null            # null if NO layer
  debug: false
  unique_id_length: 8
  min_length: 20

smoothening:
  use_assign_id_output: true
  perform_smoothing: true
  # When not using assign_ID output, set an alternative centerline path here.
  centerline: "C:/Users/nicolebyford/Documents/Bohn_2025/Footprint/0_BTools/v2/2_final_footprint/Bohn_FLM_1centerlines_dissolved_v2_QC.shp"
  angle_threshold: 120   # Lower threshold triggers smoothing on more vertices
  buffer_distance: 2     # Increase buffer for stronger smoothing
  num_workers: 4

split_to_plots:
  segment_area: 500  # Set if splitting_method set to area
  segment_length: 50  # Set if splitting_method set to length
  num_workers: 4
  extension_distance: 50
  max_splitter_length_buffer: 50

split_to_side:
  segment_area: ${split_to_plots.segment_area}  # Set if splitting_method set to area
  segment_length: ${split_to_plots.segment_length}  # Set if splitting_method set to length
  min_area: 5

split_to_subplots:
  segment_area: 50  # Set if splitting_method set to area
  segment_length: 10  # Set if splitting_method set to length
  num_workers: 4
  extension_distance: ${split_to_plots.extension_distance}  # Must be the same as the split_to_plots extension_distance
  max_splitter_length_buffer: 10
  use_smooth_centerline: true