### this is workflow.yaml
### /home/irina/SegLine/src/config/paths.yaml

dataset:
  ground_footprint: "/media/irina/My Book/Petronas/DATA/vector_data/LineFootprint/PECL_seismiclines_v0.42_FLAIMcenterline_optuneII_fixFP.gpkg"
  ground_footprint_layer: null      # null if NO layer
  centerline: "/media/irina/My Book/Petronas/DATA/vector_data/LineFootprint/PECL_seismiclines_v0.42_FLAIMcenterline_optuneII.gpkg"
  centerline_layer: null            # null if NO layer
  debug: false
  unique_id_length: 8
  min_length: 20

smoothening:
  use_assign_id_output: true
  perform_smoothing: false
  # When not using assign_ID output, set an alternative centerline path here.
  centerline: "/media/irina/My Book/Carson/WanderingRiver/6_Line_Footprints/WanderingRiver_Centerline.shp"
  angle_threshold: 120   # Lower threshold triggers smoothing on more vertices
  buffer_distance: 2     # Increase buffer for stronger smoothing
  num_workers: 4

split_to_plots:
  segment_area: 100
  num_workers: 16
  extension_distance: 50
  max_splitter_length_buffer: 50

split_to_side:
  segment_area: 100
  min_area: 5

split_to_subplots:
  segment_area: 10
  num_workers: 16
  max_splitter_length_buffer: 10
  use_smooth_centerline: true