### this is workflow.yaml
### /home/irina/SegLine/src/config/paths.yaml


##### SEISMIC LINES
#dataset:
#  ground_footprint: "/media/irina/My Book/Petronas/DATA/vector_data/Final_v.042/PECL_seismiclines_v0.42_FLAIMcenterline_optuneII_19aug25_fixFP.gpkg"
#  ground_footprint_layer: null      # null if NO layer
#  centerline: "/media/irina/My Book/Petronas/DATA/vector_data/Final_v.042/PECL_seismiclines_v0.42_FLAIMcenterline_optuneII_19aug25.gpkg"
#  centerline_layer: null            # null if NO layer
#  debug: false
#  unique_id_length: 8
#  min_length: 20
#
####### ROADS
#dataset:
#  ground_footprint: "/media/irina/My Book1/CPFN_Bohn_2025/Data/vector/AOI_seismiclines_fixFP_neg1.gpkg"
#  ground_footprint_layer: null      # null if NO layer
#  centerline: "/media/irina/My Book1/CPFN_Bohn_2025/Data/vector/AOI_seismiclines.gpkg"
#  centerline_layer: null            # null if NO layer
#  debug: false
#  unique_id_length: 3
#  min_length: 20
#  width_column: "width_neg1"  # Column name for width values in your data

####### ROADS
#dataset:
#  ground_footprint: "/media/irina/My Book1/CPFN_Bohn_2025/Data/Products/FLM/FULL_seismiclines_manual_v2_fixFP.gpkg"
#  ground_footprint_layer: null      # null if NO layer
#  centerline: "/media/irina/My Book1/CPFN_Bohn_2025/Data/Products/FLM/FULL_seismiclines_manual_v2.gpkg"
#  centerline_layer: null            # null if NO layer
#  debug: false
#  unique_id_length: 6
#  min_length: 20
#  width_column: "buffer_width"  # Column name for width values in your data

###### ROADS
dataset:
  ground_footprint: "/media/irina/My Book1/LiDea_BigExperiment/vector/FLM/Footprint/lidea_centerlines_2025_sketchmapping_5mar25_est_width_buffer_narrow.gpkg"
  ground_footprint_layer: null      # null if NO layer
  centerline: "/media/irina/My Book1/LiDea_BigExperiment/vector/FLM/Footprint/lidea_centerlines_2025_sketchmapping_5mar25_est_width.gpkg"
  centerline_layer: null            # null if NO layer
  debug: false
  unique_id_length: 4
  min_length: 20
  width_column: "adjusted_width"  # Column name for width values in your data

smoothening:
  use_assign_id_output: true
  perform_smoothing: false
  # When not using assign_ID output, set an alternative centerline path here.
  centerline: "/media/irina/My Book/Petronas/DATA/vector_data/Final_v.0.88/PECL_seismiclines_v088_width.gpkg"
  angle_threshold: 120   # Lower threshold triggers smoothing on more vertices
  buffer_distance: 2     # Increase buffer for stronger smoothing
  num_workers: 4

split_to_plots:
  plot_area: 100
  num_workers: 24
  extension_distance: 100
  max_splitter_length_buffer: 50
  perpendicular_spacing: 50  # Fixed spacing in meters between perpendiculars

split_to_side:
  splitting_method: "area"   # "area" or "length"
  plot_area: 50
  segment_length: 100
  min_area: 5

split_to_subplots:
  subplot_area: 20         # Should be 1/5 of plot area!!!
  min_area_fraction: 0.06  # Merge subplots smaller than this fraction of plot_area (0.05 * 50 = 2.5 m²)
  num_workers: 24
  max_splitter_length_buffer: 50
  use_smooth_centerline: true
  perpendicular_spacing: 10  # Fixed spacing in meters between perpendiculars